#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LAB13xamarin30.Resource", IsApplication=true)]

namespace LAB13xamarin30
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::LAB13xamarin30.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::LAB13xamarin30.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::LAB13xamarin30.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::LAB13xamarin30.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::LAB13xamarin30.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::LAB13xamarin30.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::LAB13xamarin30.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::LAB13xamarin30.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::LAB13xamarin30.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::LAB13xamarin30.Resource.String.Hello;
			global::SALLab13.Resource.Animation.slide_in_right = global::LAB13xamarin30.Resource.Animation.slide_in_right;
			global::SALLab13.Resource.Animation.slide_out_left = global::LAB13xamarin30.Resource.Animation.slide_out_left;
			global::SALLab13.Resource.Drawable.ic_arrow_back = global::LAB13xamarin30.Resource.Drawable.ic_arrow_back;
			global::SALLab13.Resource.Id.webview = global::LAB13xamarin30.Resource.Id.webview;
			global::SALLab13.Resource.Layout.activity_webview = global::LAB13xamarin30.Resource.Layout.activity_webview;
			global::SALLab13.Resource.String.ApplicationName = global::LAB13xamarin30.Resource.String.ApplicationName;
			global::SALLab13.Resource.String.Hello = global::LAB13xamarin30.Resource.String.Hello;
			global::SALLab13.Resource.String.title_activity_webview = global::LAB13xamarin30.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_in_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_out_left = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dotnet = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_arrow_back = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int myButton = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int webview = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_webview = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int hello = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int title_activity_webview = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
