#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LAB10xamarin30.Resource", IsApplication=true)]

namespace LAB10xamarin30
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::LAB10xamarin30.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::LAB10xamarin30.Resource.String.Hello;
			global::SALLab10.Resource.String.ApplicationName = global::LAB10xamarin30.Resource.String.ApplicationName;
			global::SALLab10.Resource.String.Hello = global::LAB10xamarin30.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int XamarinDiplomado = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int ClickCounter = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int ClickMe = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int ContentHeader = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int Validar = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int a = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int btn = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int etCorreo = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int etPassword = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int imageView1 = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout1 = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int textView2 = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int txview = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Validar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f070000
			public const int numberOfClicks = 2131165184;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int sound = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ButtonText = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ContentHeader = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int Validar = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int email = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int pass = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
